export { default as CatalogView } from "./Catalog/CatalogView/CatalogView"
export { default as SettingsView } from "./Settings/SettingsView/SettingsView"
export { default as NotesView } from "./Notes/NotesView/NotesView"
export { default as CUNotesView } from "./Notes/CUNotesView/CUNotesView"
export { default as InventoriesView } from "./Inventories/InventoriesView/InventoriesView"
export { default as DashBoardView } from "./Dashboard/DashBoardView/DashBoardView"
export { default as LoginView } from "./LoginView/LoginView"
export { default as MoreView } from "./MoreView/MoreView"
export { default as CURawMaterialView } from "./Catalog/CURawMaterialView/CURawMaterialView"
export { default as CUFabricatedView } from "./Catalog/CUFabricatedView/CUFabricatedView"
export { default as CUServicesView } from "./Catalog/CUServicesView/CUServicesView"
export { default as TransactionsView } from "./Catalog/TransactionsView/TransactionsView"
export { default as DetailNotesView } from "./Notes/DetailNotesView/DetailNotesView"
export { default as DetailInventoriesView } from "./Inventories/DetailInventoriesView/DetailInventoriesView"
export { default as CInventoriesView } from "./Inventories/CInventoriesView/CInventoriesView"
export { default as CUSellersView } from "./Sellers/CUSellersView/CUSellersView";
export { default as SellersView } from "./Sellers/SellersView/SellersView";
export { default as CUCustomersView } from "./Customers/CUCustomersView/CUCustomersView";
export { default as CustomersView } from "./Customers/CustomersView/CustomersView";
export { default as UCompanyView } from "./Company/UCompanyView/UCompanyView";
export { default as AboutView } from "./AboutView/AboutView";
